#!/usr/bin/env node
/**
 * Move every wappa package to a different npm scope, everywhere at once: package names,
 * internal dependency ranges, imports in source and tests, docs, and the scaffolder's
 * templates. npm only confirms an org name when you create it, so if your first choice is
 * taken, rerun this with the next one.
 *
 *   node scripts/rename-scope.mjs wappajs        # @wappajs/core -> @wappajs/core
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';

const next = (process.argv[2] ?? '').replace(/^@/, '');
if (!/^[a-z0-9][a-z0-9-._]*$/.test(next)) {
  console.error('usage: node scripts/rename-scope.mjs <new-scope>   (npm scopes are lowercase)');
  process.exit(1);
}

/** Read the scope currently in use from the core package, so this is rerunnable. */
const current = JSON.parse(readFileSync('packages/core/package.json', 'utf8')).name.split('/')[0];
if (current === `@${next}`) {
  console.log(`already @${next} — nothing to do`);
  process.exit(0);
}

const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', 'coverage']);
const EXTS = new Set(['.ts', '.tsx', '.js', '.mjs', '.json', '.md', '.tmpl', '.yml', '.yaml']);

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) yield* walk(path);
    else if (EXTS.has(extname(path)) || entry.endsWith('.tmpl')) yield path;
  }
}

const escaped = current.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
// Match `@scope/pkg` and the bare `@scope` (quoted, as in path.join(..., '@scope', dep)).
const pattern = new RegExp(`${escaped}(?=/)|${escaped}(?=['"\`])`, 'g');
let changed = 0;

for (const path of walk('.')) {
  // The lockfile is regenerated by `npm install`, not hand-edited.
  if (path === './package-lock.json') continue;
  const before = readFileSync(path, 'utf8');
  const after = before.replace(pattern, `@${next}`);
  if (before !== after) {
    writeFileSync(path, after);
    changed++;
  }
}

console.log(`${current}/* -> @${next}/*  in ${changed} files`);
console.log('next: npm install && npm run build && npm test');
